markdown: rdiscount
permalink: /:title/
url: http://blog.xulingmin.com/
name: xiedantibu
author: xiedantibu
qq: 804322011
email: xiedantibu@hotmail.com
duoshuo: xiedantibu
beian: 
weibo: 1701186332
github: xiedantibu
pygments: true
safe: true
paginate: 20
about: "博客开张了啊"
