markdown: redcarpet
redcarpet:
    extensions: ["tables"]
permalink: /:title/
url: http://blog.xulingmin.com/
name: xiedantibu
author: xiedantibu
qq: 804322011
email: xiedantibu@hotmail.com
duoshuo: xiedantibu
beian:
weibo: 1701186332
github: xiedantibu
highlighter: true
safe: true
paginate: 20
about: "博客开张了啊"
gems: [jekyll-paginate]
